resources:
- repo: self
trigger:
- build-refactor
jobs:

- job: Style
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: AzureCLI@1
    displayName: 'Style Check'
    inputs:
      azureSubscription: 'Findable Incubation(ca9d21ff-2a46-4e8b-bf06-8d65242342e5)'
      scriptLocation: inlineScript
      inlineScript: 'sbt scalastyle test:scalastyle'

- job: UnitTests
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: AzureCLI@1
    displayName: 'Setup repo'
    inputs:
      azureSubscription: 'Findable Incubation(ca9d21ff-2a46-4e8b-bf06-8d65242342e5)'
      scriptLocation: inlineScript
      inlineScript: 'sbt setup'
  - task: AzureCLI@1
    displayName: 'Unit Test'
    inputs:
      azureSubscription: 'Findable Incubation(ca9d21ff-2a46-4e8b-bf06-8d65242342e5)'
      scriptLocation: inlineScript
      inlineScript: 'sbt test'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/test-reports/*.xml'
    inputs:
      testResultsFiles: '**/test-reports/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
