#!/bin/bash

export OPENMPI_VERSION="3.1.2"
export SPARK_VERSION="3.3.2"
export HADOOP_VERSION="3.3"
export SYNAPSEML_VERSION="0.11.4" # Binder compatibility version

echo "Beginning Spark Session..."
exec "$@"
