print("attempting require")
flush.console()
Sys.sleep(1)
if (!require("sparklyr")) {
  print("attempting packages.install")
  flush.console()
  Sys.sleep(1)
  packages.install("sparklyr")
  print("attempting library")
  flush.console()
  Sys.sleep(1)
  library("sparklyr")
}
print(spark_available_versions(show_hadoop=TRUE, show_minor=TRUE))
flush.console()
Sys.sleep(1)
#spark_install(version = "3.2.2", hadoop_version = "3.2")
tryCatch({
  print("running spark_install_find")
  flush.console()
  Sys.sleep(1)
  spark_install_find(version = "3.2.2", hadoop_version = "3.2")
  flush.console()
  Sys.sleep(1)
  print("ran spark_install_find")  
  flush.console()
  Sys.sleep(1)
},
error=function(err) {
  print("Installing ../../../../../../../spark-3.2.2-bin-hadoop3.2.tgz")
  flush.console()
  Sys.sleep(1)
  spark_install_tar("../../../../../../../spark-3.2.2-bin-hadoop3.2.tgz")
  flush.console()
  Sys.sleep(1)
  print("installed ../../../../../../../spark-3.2.2-bin-hadoop3.2.tgz")
  flush.console()
  Sys.sleep(1)
})
options("testthat.output_file" = "../../../../r-test-results.xml")
tryCatch({
#  print("calling spark_home_set")
#  flush.console()
#  Sys.sleep(1)
#  sparklyr::spark_home_set()
#  flush.console()
#  Sys.sleep(1)
  wd2 = getwd()
  print(paste(" +++ wd: ", wd2))
  print(list.files(wd2, full.names=TRUE, recursive=TRUE)  
  flush.console()
  Sys.sleep(1)
  print(paste("wd exists: ", dir.exists(wd2)))
  print(paste("DESCRIPTION exists: ", file.exists(file.path(getwd(), "DESCRIPTION"))))
  dir = sparklyr::spark_install_dir()
  print(paste("spark_install_dir: ", dir))
  print(list.files(dir, full.names=TRUE))
  flush.console()
  Sys.sleep(1)
#  print(paste("SPARK_HOME=", Sys.getenv("SPARK_HOME")))
  print("set wd")
  flush.console()
  Sys.sleep(1)
  setwd(getwd())
  print("call test")
  flush.console()
  Sys.sleep(1)
  devtools::test(reporter = JunitReporter$new())
  print("ran test")
  flush.console()
  Sys.sleep(1)
},
error = function(err) {
  flush.console()
  Sys.sleep(1)
  print(paste("Error: ", err))
  flush.console()
  Sys.sleep(1)
  stop(err)
})