#!/usr/bin/env bash
# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in project root for information.

. "$(dirname "${BASH_SOURCE[0]}")/../../runme" "$@"
@ "shared.sh"
main() {

show section "Running Generated Python Tests"
local testdir="$TEST_RESULTS/generated_pytests" t status=0
cd "$testdir"
for t in *"_tests.py"; do
  printf "\n\n==================== %s ====================\n" "$t"
  _pytest "$t" || status=$?
done
if ((status)); then failwith "failures in generated python tests"; fi

}
main "$@"
