#!/usr/bin/env bash
# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in project root for information.

. "$(dirname "${BASH_SOURCE[0]}")/../../runme" "$@"
@ "shared.sh"

show section "Running Local Notebook Tests"
cd "$TEST_RESULTS/notebook_tests/local"
_ cp -a "$BASEDIR/tools/notebook/tester/"* .
_pytest "TestNotebooksLocally.py" || failwith "failures in local notebook tests"
