steps:
  - bash: |
      set -e
      curl -s https://codecov.io/bash > .codecov
      chmod +x .codecov
      echo "Starting Codecov Upload"
      ./.codecov -t $(codecov-token)
    displayName: Upload Coverage Report To Codecov.io
    condition: succeededOrFailed()
