steps:
  - bash: |
      set -e
      curl -Os https://cli.codecov.io/latest/linux/codecov
      chmod +x codecov
      echo "Starting Codecov Upload"
      ./codecov --verbose upload-process -t $(codecov-token) --dir .
      echo "Codecov Upload Complete" # Ensure that uploading failure does not stop the pipeline
    retryCountOnTaskFailure: 1
    displayName: Upload Coverage Report To Codecov.io
    condition: succeededOrFailed()
