steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
    retryCountOnTaskFailure: 1
  - bash: |
      mkdir -p $(CONDA_CACHE_DIR)
      sudo chown -R $(whoami):$(id -ng) $(CONDA_CACHE_DIR)
    displayName: Fix directory permissions
  - task: Cache@2
    displayName: Use cached Anaconda environment
    inputs:
      key: 'conda | "$(Agent.OS)" | environment.yml'
      restoreKeys: |
        python | "$(Agent.OS)"
        python
      path: $(CONDA_CACHE_DIR)
      cacheHitVar: CONDA_CACHE_RESTORED
    timeoutInMinutes: 20
    retryCountOnTaskFailure: 1
  - bash: |
      (timeout 30m conda env create --yes -f environment.yml -v)  || (timeout 30m conda env create --yes -f environment.yml -v)
    displayName: Create Anaconda environment
    retryCountOnTaskFailure: 1
    condition: eq(variables.CONDA_CACHE_RESTORED, 'false')
  - bash: |
        echo "system usage:"
        sudo df -h 
        echo "conda cache usage:"
        sudo du -h --max-depth=1 $(CONDA_CACHE_DIR)
    displayName: Display disk usage
