// Copyright (C) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in project root for information.

package com.microsoft.ml.spark.codegen

import com.microsoft.ml.spark.FileUtilities._
import Config._
import DocGen._
import WrapperClassDoc._

import scala.util.matching.Regex
import java.util.regex.Pattern
import org.apache.commons.io.FilenameUtils._

object CodeGen {

  def copyAllFiles(fromDir: File, rx: Regex, toDir: File): Unit = {
    if (!fromDir.isDirectory) { println(s"'$fromDir' is not a directory"); return }
    allFiles(fromDir, if (rx == null) null else (f => rx.findFirstIn(f.getName) != None))
      .foreach{x => copyFile(x, toDir, overwrite=true)}
  }
  def copyAllFiles(fromDir: File, extension: String, toDir: File): Unit =
      copyAllFiles(fromDir,
                   if (extension == null || extension == "") null
                   else (Pattern.quote("." + extension) + "$").r,
                   toDir)

  def copyAllFilesFromRoots(fromDir: File, roots: List[String], relPath: String,
                            extension: String, toDir: File): Unit = {
    roots.foreach { root =>
      val dir = new File(new File(fromDir, root), relPath)
      if (dir.exists && dir.isDirectory) copyAllFiles(dir, extension, toDir)
    }
  }
  def copyAllFilesFromRoots(fromDir: File, roots: List[String], relPath: String,
                            rx: Regex, toDir: File): Unit = {
    roots.foreach { root =>
      val dir = new File(new File(fromDir, root), relPath)
      if (dir.exists && dir.isDirectory) copyAllFiles(dir, rx, toDir)
    }
  }

  def generateArtifacts(): Unit = {
    println(s"""|Running registration with config:
                |  topDir:    $topDir
                |  srcDir:    $srcDir
                |  outputDir: $outputDir
                |  toZipDir:  $toZipDir
                |  pyTestDir: $pyTestDir
                |  docDir:    $docDir""".stripMargin)
    val roots = // note: excludes the toplevel project
      if (!rootsFile.exists) sys.error(s"Could not find roots file at $rootsFile")
      else readFile(rootsFile, _.getLines.toList).filter(_ != ".")
    println("Creating temp folders")
    toZipDir.mkdirs
    pyTestDir.mkdirs
    docDir.mkdirs
    inDocDir.mkdirs
    println("Copy jar files to output directory")
    copyAllFilesFromRoots(srcDir, roots, jarRelPath,
                          (Pattern.quote("-" + mmlVer + ".jar") + "$").r,
                          outputDir)
    println("Copy source python files")
    copyAllFilesFromRoots(srcDir, roots, pyRelPath, "py", toZipDir)
    println("Generate python APIs")
    PySparkWrapperGenerator()
    println("Generate .rst files for the python APIs for autogenerated documentation")
    genRstFiles()
    // build init file
    val pattern = new Regex("^[a-zA-Z]\\w*.py$")
    val importStrings =
      allFiles(toZipDir, (f => pattern.findFirstIn(f.getName) != None))
        .map(f => s"from mmlspark.${getBaseName(f.getName)} import *\n").mkString("")
    writeFile(new File(toZipDir, "__init__.py"), packageHelp(importStrings))
    // package python zip file
    zipFolder(toZipDir, zipFile)
    // leave the source files there so they will be included in the super-jar
    // if (!delTree(toZipDir)) println(s"Error: could not delete $toZipDir")
  }

  def main(args: Array[String]): Unit = {
    org.apache.log4j.BasicConfigurator.configure(new org.apache.log4j.varia.NullAppender())
    generateArtifacts()
  }

}
