name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@8d0ead9b49a65aa66dac6949b1ff149d7ef8b4de # v2.5
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "msdata"
          ado_project: "A365"
          ado_area_path: '${{ secrets.ADO_AREA_PATH }}'
          ado_wit: "Task"
          ado_new_state: "To Do"
          ado_active_state: "In Progress"
          ado_close_state: "Done"
          ado_bypassrules: true
