name: PythonTests

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    strategy:
      matrix:
        project: ["core", "deepLearning", "lightgbm", "opencv", "vw", "cognitive"]
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.8.8
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.8.8
        environment-file: environment.yaml
        activate-environment: synapseml
    - name: Install Pip Package
      shell: bash
      run: |
        (timeout 5m sbt setup) || (echo "retrying" && timeout 5m sbt setup) || (echo "retrying" && timeout 5m sbt setup)
        sbt installPipPackage
    - name: Test Python Code
      shell: bash
      run: (sbt "project ${{ matrix.project }}" coverage testPython) || (sbt "project ${{ matrix.project }}" coverage testPython) || (sbt "project ${{ matrix.project }}" coverage testPython)
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/python-test-*.xml'
    - name: Generate Codecov report
      if: always()
      shell: bash
      run: sbt coverageReport
    - name: Get Codecov Secret from Key Vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "mmlspark-keys"
        secrets: 'codecov-token'
      id: GetKeyVaultSecrets
    - name: Upload Coverage Report To Codecov.io
      if: always()
      shell: bash
      run: |
        set -e
        curl -s https://codecov.io/bash > .codecov
        chmod +x .codecov
        echo "Starting Codecov Upload"
        ./.codecov -t ${{ steps.GetKeyVaultSecrets.outputs.codecov-token }}
