name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run scalastyle
      run: sbt scalastyle test:scalastyle
      
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Key Vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: mmlspark-keys
          secrets: "storage-key, nexus-un, nexus-pw, pgp-private, pgp-public, pgp-pw"
      - run: echo "##vso[task.prependpath]$CONDA/bin"
      - name: Add conda to PATH
      - run: conda info
      - run: conda env create -f environment.yaml
      - name: Create Anaconda environment
      
      
