name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
      - name: Azure Login
        uses: Azure/cli@v1
        with:
          inlineScript: az login --service-principal -u ${{ secrets.SYNAPSEML_BUILD_SP_APPID }} -p ${{ secrets.SYNAPSEML_BUILD_SP_PASSWORD }} --tenant ${{ secrets.SYNAPSEML_BUILD_SP_TENANTID }}
      - name: Azure Key Vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: mmlspark-keys
          secrets: "storage-key, nexus-un, nexus-pw, pgp-private, pgp-public, pgp-pw"
