name: Full SynapseML Pipeline

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  ScalaStyle:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run scalastyle
      run: sbt scalastyle test:scalastyle
  
  Publish:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "mmlspark-keys"
        secrets: 'storage-key,nexus-un,nexus-pw,pgp-private,pgp-public,pgp-pw'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: GetKeyVaultSecrets
    - name: Setup Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.8.8
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.8.8
        environment-file: environment.yaml
        activate-environment: synapseml
    - name: Publish Artifact
      shell: bash -l {0}
      run: |
        set -e
        sbt packagePython
        sbt publishBlob publishDocs publishR publishPython
        sbt publishSigned
        sbt genBuildInfo
      env:
        STORAGE-KEY: ${{ steps.GetKeyVaultSecrets.outputs.storage-key }}
        NEXUS-UN: ${{ steps.GetKeyVaultSecrets.outputs.nexus-un }}
        NEXUS-PW: ${{ steps.GetKeyVaultSecrets.outputs.nexus-pw }}
        PGP-PRIVATE: ${{ steps.GetKeyVaultSecrets.outputs.pgp-private }}
        PGP-PUBLIC: ${{ steps.GetKeyVaultSecrets.outputs.pgp-public }}
        PGP-PW: ${{ steps.GetKeyVaultSecrets.outputs.pgp-pw }}
    - name: Publish Badges
      if: success()
      shell: bash -l {0}
      run: |
        set -e
        sbt publishBadges
      env:
        STORAGE-KEY: ${{ steps.GetKeyVaultSecrets.outputs.storage-key }}
        NEXUS-UN: ${{ steps.GetKeyVaultSecrets.outputs.nexus-un }}
        NEXUS-PW: ${{ steps.GetKeyVaultSecrets.outputs.nexus-pw }}
        PGP-PRIVATE: ${{ steps.GetKeyVaultSecrets.outputs.pgp-private }}
        PGP-PUBLIC: ${{ steps.GetKeyVaultSecrets.outputs.pgp-public }}
        PGP-PW: ${{ steps.GetKeyVaultSecrets.outputs.pgp-pw }}
