name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
      - name: Azure Login
        uses: Azure/cli@v1
        with:
          inlineScript: az login --service-principal -u ${{ secrets.SYNAPSEML_BUILD_SP_APPID }} -p ${{ secrets.SYNAPSEML_BUILD_SP_PASSWORD }} --tenant ${{ secrets.SYNAPSEML_BUILD_SP_TENANTID }}
