name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ScalaStyle:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run scalastyle
      run: sbt scalastyle test:scalastyle
      
  Publish:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
      - name: Azure Key Vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: mmlspark-keys
          secrets: "storage-key, nexus-un, nexus-pw, pgp-private, pgp-public, pgp-pw"
      - run: echo "##vso[task.prependpath]$CONDA/bin"
        name: Add conda to PATH
      - run: conda info
      - run: conda env create -f environment.yaml
        name: Create Anaconda environment
      - run: |
          set -e
          source activate synapseml
          sbt packagePython
          sbt publishBlob publishDocs publishR publishPython
          sbt publishSigned
          sbt genBuildInfo
          echo "##vso[task.uploadsummary]$(pwd)/target/Build.md"
        name: Publish Artifacts
        env:
          STORAGE-KEY: $(storage-key)
          NEXUS-UN: $(nexus-un)
          NEXUS-PW: $(nexus-pw)
          PGP-PRIVATE: $(pgp-private)
          PGP-PUBLIC: $(pgp-public)
          PGP-PW: $(pgp-pw)
      - run: |
          set -e
          sbt publishBadges
        name: Publish Badges
        env:
          STORAGE-KEY: $(storage-key)
          NEXUS-UN: $(nexus-un)
          NEXUS-PW: $(nexus-pw)
          PGP-PRIVATE: $(pgp-private)
          PGP-PUBLIC: $(pgp-public)
          PGP-PW: $(pgp-pw)
      
      
