name: CI/Website Auto Deployment

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "mmlspark-keys"
        secrets: 'gh-name,gh-email,gh-token'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: GetKeyVaultSecrets
    - name: 'Install Node.js'
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setup Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.8.8
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.8.8
        environment-file: environment.yaml
        activate-environment: synapseml
    - name: Convert notebooks to markdowns
      shell: bash
      run: sbt convertNotebooks
    - name: yarn install and build
      shell: bash
      run: |
        set -e
        yarn install
        cd website
        yarn
        yarn build
    - name: yarn deploy
      if: success()
      shell: bash
      run: |
        set -e
        git config --global user.name "${GH_NAME}"
        git config --global user.email "${GH_EMAIL}"
        git checkout -b main
        echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        cd website
        GIT_USER="${GH_NAME}" yarn deploy
      env:
        GH_NAME: $(gh-name)
        GH_EMAIL: $(gh-email)
        GH_TOKEN: $(gh-token)
