name: Remove awaiting response label

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.author_association != 'OWNER' &&
      github.event.comment.author_association != 'COLLABORATOR'
    steps:
      - name: Remove needs-reply label
        uses: octokit/request-action@02f5e7c637a73a3b12ed81015fa7fb5f11cc5d7d # v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: "awaiting response"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}