library(sparklyr)
config <- spark_config()
options(sparklyr.log.console = TRUE)
options(sparklyr.verbose = TRUE)
Sys.setenv(SPARK_HOME = "~/bin/spark-3.2.0-bin-hadoop3.2/")
sc <- spark_connect(master = "local", version="3.2.0", config = config)
